name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${GITHUB_REF#refs/heads/}
      - run: echo "${GITHUB_REF#refs/heads/}"
