name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Capture triggering branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Comment contains trigger
        uses: promiseofcake/circleci-trigger-action@v1
        if: contains(github.event.comment.body, 'typescript-report')
        with:
          user-token: ${{ secrets.CIRCLECI_TOKEN }}
          project-slug: promiseofcake/circleci-trigger-action
          branch: ${{ env.BRANCH_NAME }}
          payload: '{"run_output_workflow": true}'
