name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Comment contains trigger
        uses: './.github/workflows/actions/'
        if: contains(github.event.comment.body, 'typescript-report')
        with:
          token: ${{ secrets.CIRCLE_CI_TOKEN }}
          who-to-greet: 'Me'
